### ISSUE TITLE
still being maintained? and question

### ISSUE THREAD

**Issue by warior456** [jadestudios/discord-music-player#12]
does this fork improve loading times of songs and Spotify playlists?

**Comment by thenerdoflight** [comment]
Hello @warior456, this fork is still being maintained. 
This fork does not improve loading times of songs, but it does improve loading stability. I have not ran into an issue with loading times albeit that is single loadings and not bulk.

I am unsure about Spotify playlists since I do not use Spotify.

**Comment by warior456** [comment]
how do i install this one with npm?

**Comment by warior456** [comment]
i saw this one also fixes a security issue and the main one seems unmaintained

**Comment by thenerdoflight** [comment]
Closing, original question asked and answered.

To install via NPM: (it's also on the readme btw)
`npm install --save @jadestudios/discord-music-player`
